### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-avsdf#2]
It is confusing how the layout animates. The initial placement of nodes on the circle is animated like we normally do when "animate" is "end". The remaining part where we do local swaps occurs very fast and acts like we do "animate" is "during". Let's discuss how we do this and should do it.

**Comment by ugurdogrusoz** [comment]
Let's change this as discussed in a meeting.

**Comment by alihanokka** [comment]
"During" animation is now uniform.
